from pathlib import Path
import re

java_dir = Path("android/app/src/main/java/com/shanpalia/paliaapkhub")
java_dir.mkdir(parents=True, exist_ok=True)

src = Path("native-download-plugin/src/main/java/com/shanpalia/paliaapkhub/PaliaDownloaderPlugin.java")
dst = java_dir / "PaliaDownloaderPlugin.java"
if not src.exists():
    raise SystemExit("Native PaliaDownloaderPlugin.java is missing")
dst.write_bytes(src.read_bytes())

main = java_dir / "MainActivity.java"
if not main.exists():
    raise SystemExit("MainActivity.java was not generated by Capacitor")

text = main.read_text(encoding="utf-8")
imp = "import com.shanpalia.paliaapkhub.PaliaDownloaderPlugin;"
if imp not in text:
    text = text.replace("import com.getcapacitor.BridgeActivity;", "import com.getcapacitor.BridgeActivity;\n" + imp)

reg = "registerPlugin(PaliaDownloaderPlugin.class);"
if reg not in text:
    # Insert before the final class closing brace.
    pos = text.rfind("}")
    if pos < 0:
        raise SystemExit("MainActivity class closing brace not found")
    insertion = "\n    @Override\n    public void onCreate(android.os.Bundle savedInstanceState) {\n        super.onCreate(savedInstanceState);\n        registerPlugin(PaliaDownloaderPlugin.class);\n    }\n"
    text = text[:pos] + insertion + text[pos:]
main.write_text(text, encoding="utf-8")

res_xml = Path("android/app/src/main/res/xml")
res_xml.mkdir(parents=True, exist_ok=True)
(res_xml / "palia_file_paths.xml").write_text("""<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-files-path name="palia_external_files" path="." />
</paths>
""", encoding="utf-8")

manifest = Path("android/app/src/main/AndroidManifest.xml")
m = manifest.read_text(encoding="utf-8")

if "android.permission.REQUEST_INSTALL_PACKAGES" not in m:
    match = re.search(r"<manifest\\b[^>]*>", m)
    if not match:
        raise SystemExit("Could not find opening <manifest> tag")
    m = m[:match.end()] + '\n    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />' + m[match.end():]

provider = """        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/palia_file_paths" />
        </provider>
"""
if "androidx.core.content.FileProvider" not in m:
    pos = m.rfind("</application>")
    if pos < 0:
        raise SystemExit("application tag missing")
    m = m[:pos] + provider + m[pos:]
manifest.write_text(m, encoding="utf-8")

gradle = Path("android/app/build.gradle")
g = gradle.read_text(encoding="utf-8")
if "androidx.core:core:" not in g:
    if "dependencies {" in g:
        g = g.replace("dependencies {", "dependencies {\n    implementation 'androidx.core:core:1.15.0'", 1)
    else:
        g += "\n\ndependencies { implementation 'androidx.core:core:1.15.0' }\n"
gradle.write_text(g, encoding="utf-8")

print("App-owned native downloader configured.")
